CREATE TABLE users (
                       user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       username VARCHAR(255)
);