CREATE TABLE tasks (
                       task_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(255) NOT NULL,
                       description TEXT NOT NULL,
                       status VARCHAR(50) NOT NULL,
                       priority VARCHAR(50) NOT NULL,
                       author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                       executor_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       due_date TIMESTAMP,
                       CONSTRAINT chk_status_valid CHECK (status IN ('WAITING', 'IN_PROGRESS', 'COMPLETED')),
                       CONSTRAINT chk_priority_valid CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW'))
);