CREATE TABLE comments (
                          comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          text TEXT NOT NULL,
                          author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                          task_id BIGINT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);